version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'

  app:
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
