version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '3002:3002'

  # app:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
