import { DataObject } from './parser/parsers/types';

export function initializeDataObject(): DataObject {
  return {
    link: '',
    address: '',
    city: '',
    district: '',
    historicalDistrict: '',
    metro: '',
    street: '',
    houseNumber: '',
    description: '',
    footMetro: 0,
    carMetro: 0,
    price: 0,
    propid: 0,
    dateposted: new Date(),
    ownerID: 0,
    phone: '',
    housingType: '',
    totalArea: 0,
    livingArea: 0,
    kitchenArea: 0,
    ceilingHeight: 0,
    bathroom: '',
    balcony: false,
    viewFromWindows: '',
    renovation: '',
    year: 0,
    buildingSeries: '',
    elevatorCount: 0,
    buildingType: '',
    overlapType: '',
    parking: '',
    entrances: 0,
    heating: '',
    emergency: false,
    floor: 0,
    totalFloors: 0,
    cianPrice: 0,
    serviceName: '',
    rooms: 0,
    pricePerMeter: 0,
    lat: 0.1,
    lng: 0.1,
    isByOwner: false,
    updated: new Date(),
    scrapedAt: new Date(),
  };
}
